import matplotlib.pyplot as plt
import os
import sys
# this program is for graphing the data generated by
# my multithreaded mergesort program
# Programmer: Matthew Stroble

if __name__ == "__main__":
    # Settings - Adjust if needed
    # sets the size of the starting array to be tested
    arrayStart = 0

    # last array size to be tested
    arrayMax = 500000000

    # How much to grow the array for the next set of array size to be tested
    stepSize = 50000000

    # Y-axis time scale for output graph, if array size being tested < 1000 use 0.01 if arrayMax > 5000 use 1
    # TODO allows system to auto set time scale based on arrayMax.
    timeScaleFactor = 210



    RUNRANGE = []
    # setting up data storage
    serialmergesortData = []
    multithreadedMergesortData = []
    currentMultiThreadFile = []

    print("Reading Data from files")

    serialFile = open(os.path.join(sys.path[0], "serialData.txt"), 'r')

    for i in serialFile:
        serialmergesortData.append(float(i[:-1]))
    serialFile.close()

    for i in range(2, 9):
        multiThreadedFile = open(os.path.join(sys.path[0], "multiThreadedData_" + str(i) + ".txt"), 'r')
        multithreadedMergesortData.append([])
        for line in multiThreadedFile:
            multithreadedMergesortData[i - 2].append(float(line[:-1]))



        multiThreadedFile.close()

    for i in range(stepSize, arrayMax + stepSize, stepSize):
        RUNRANGE.append(i)

    for i in multithreadedMergesortData:
        print(i)



    plt.plot(RUNRANGE, serialmergesortData, 'b-', label='Single Threaded Mergesort')
    plt.plot(RUNRANGE, multithreadedMergesortData[0], 'm-', label='2 Threaded Mergesort')
    plt.plot(RUNRANGE, multithreadedMergesortData[1], 'g-', label='3 Threaded Mergesort')
    plt.plot(RUNRANGE, multithreadedMergesortData[2], 'r-', label='4 Threaded Mergesort')
    plt.plot(RUNRANGE, multithreadedMergesortData[3], 'y-', label='5 Threaded Mergesort')
    plt.plot(RUNRANGE, multithreadedMergesortData[4], 'b-', label='6 Threaded Mergesort')
    plt.plot(RUNRANGE, multithreadedMergesortData[5], 'y-o', label='7 Threaded Mergesort')
    plt.plot(RUNRANGE, multithreadedMergesortData[6], 'm-o', label='8 Threaded Mergesort')


    plt.axis([arrayStart, arrayMax, 0, timeScaleFactor])
    plt.xlabel("Worst Case Decending Order")
    plt.ylabel("Time from default_timer (walltime)")
    plt.title("Matthew Stroble")
    plt.legend(loc='upper left', shadow=False, fontsize='small')
    plt.show()
